# -*- coding: utf-8 -*-
"""Bertpractice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dez7RoXSxYhUqPZ2dfnGmDVOVCMh0GZb
"""

pip install torch transformers datasets seqeval

from transformers import AutoTokenizer, AutoModelForTokenClassification

model_name = "bert-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name, num_labels=9)

text = "Virat Kohli plays for India."

inputs = tokenizer(text, return_tensors="pt")  # pt = PyTorch
print(inputs)

outputs = model(**inputs)
logits = outputs.logits
print(logits.shape)

!pip install transformers

from transformers import AutoTokenizer, AutoModelForTokenClassification

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
model = AutoModelForTokenClassification.from_pretrained('bert-base-cased', num_labels=9)

text = "Virat Kohli plays for India."
inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)
logits = outputs.logits
print(logits.shape)

# Example dataset:
sentences = [
    "Virat Kohli plays for India.",
    "Messi is a great footballer."
]

labels = [
    ["B-PER", "I-PER", "O", "O", "B-LOC", "O"],
    ["B-PER", "O", "O"]
]

from transformers import AutoTokenizer
import torch

# Initialize tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

# Example sentences and labels
sentences = [
    ["Virat", "Kohli", "plays", "for", "India", "."],
    ["Messi", "is", "a", "great", "footballer", "."]
]

labels = [
    ["B-PER", "I-PER", "O", "O", "B-LOC", "O"],
    ["B-PER", "O", "O", "O", "O", "O"]
]

# Define the label-to-ID mapping
label2id = {
    "O": 0,
    "B-PER": 1,
    "I-PER": 2,
    "B-LOC": 3,
    "I-LOC": 4,
    # Add more labels as needed
}

# Convert string labels to IDs
def convert_labels_to_ids(labels, label2id):
    return [[label2id[label] for label in sentence_labels] for sentence_labels in labels]

aligned_labels = convert_labels_to_ids(labels, label2id)

# Function to tokenize and align labels
def tokenize_and_align_labels(sentences, labels):
    tokenized_inputs = tokenizer(sentences, truncation=True, padding=True, is_split_into_words=True, return_tensors="pt")

    # Align labels to the tokenized words
    new_labels = []
    for i, label in enumerate(labels):
        word_ids = tokenized_inputs.word_ids(i)  # Get word ids for each sentence
        new_label = []
        previous_word_idx = None
        for word_idx in word_ids:
            if word_idx is None:
                new_label.append(-100)  # Ignore special tokens like [CLS], [SEP]
            elif word_idx != previous_word_idx:
                new_label.append(label[word_idx])  # Assign label to the first token of each word
            else:
                new_label.append(label[word_idx])  # For sub-words, repeat the same label
            previous_word_idx = word_idx
        new_labels.append(new_label)

    return tokenized_inputs, new_labels

# Tokenize and align labels
tokenized_inputs, aligned_labels = tokenize_and_align_labels(sentences, aligned_labels)

# Convert tokenized inputs and aligned labels into a PyTorch dataset
class NERDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]).clone().detach() for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx]).clone().detach()
        return item

    def __len__(self):
        return len(self.labels)


# Create dataset object
dataset = NERDataset(tokenized_inputs, aligned_labels)

# Checking the dataset object
print(dataset[0])

from transformers import Trainer, TrainingArguments

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",          # output directory
    num_train_epochs=3,              # number of training epochs
    per_device_train_batch_size=8,   # batch size for training
    per_device_eval_batch_size=8,    # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir="./logs",            # directory for storing logs
)

# Initialize the Trainer
trainer = Trainer(
    model=model,                     # the model to be trained
    args=training_args,              # training arguments
    train_dataset=dataset,           # training dataset
)

trainer.train()

from sklearn.model_selection import train_test_split

# Assuming `dataset` is your training dataset object
train_dataset, eval_dataset = train_test_split(dataset, test_size=0.2)  # Split 80% for training and 20% for evaluation

trainer = Trainer(
    model=model,                      # the model to be trained
    args=training_args,               # training arguments
    train_dataset=train_dataset,      # training dataset
    eval_dataset=eval_dataset         # evaluation dataset
)

# Evaluate the model
results = trainer.evaluate()

# Print results
print(results)

model.save_pretrained("./final_model")
tokenizer.save_pretrained("./final_model")

from transformers import AutoModelForTokenClassification, AutoTokenizer
from transformers import pipeline

# Load model and tokenizer
model_name = "dbmdz/bert-large-cased-finetuned-conll03-english"
model = AutoModelForTokenClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Create NER pipeline
nlp_ner = pipeline("ner", model=model, tokenizer=tokenizer)

# Function to run Named Entity Recognition
def detect_entities(text):
    entities = nlp_ner(text)
    return entities

# Get input text
text = input("Enter the text for NER: ")

# Run detection
entities = detect_entities(text)

# Display detected entities
print("\nDetected Entities:")
for entity in entities:
    print(f"Entity: {entity['entity']}, Score: {entity['score']:.3f}, Word: '{entity['word']}', Start: {entity['start']}, End: {entity['end']}")

!apt-get install git